repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^(infrared_protocols|tests)/
      - id: ruff-format
        files: ^(infrared_protocols|tests)/

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.39.10
    hooks:
      - id: basedpyright
        files: ^(infrared_protocols|tests)/
        additional_dependencies:
          - pytest

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
